// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwkHNKUgGy68zBYMIFtq66A2lRhISDuzE',
    appId: '1:311082447008:web:ba8ed190a2fb66e6fe99c5',
    messagingSenderId: '311082447008',
    projectId: 'gym-training-app-2f9d8',
    authDomain: 'gym-training-app-2f9d8.firebaseapp.com',
    storageBucket: 'gym-training-app-2f9d8.appspot.com',
    measurementId: 'G-VSCQ59Z93V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhVICVxZDylSAE1Voy_yqyv9IN_gnrnFE',
    appId: '1:311082447008:android:f884719c124774bcfe99c5',
    messagingSenderId: '311082447008',
    projectId: 'gym-training-app-2f9d8',
    storageBucket: 'gym-training-app-2f9d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEA-_zQU8y1uTn2EVP4s-BIC1kT7tYZ9I',
    appId: '1:311082447008:ios:edaa5950149052f0fe99c5',
    messagingSenderId: '311082447008',
    projectId: 'gym-training-app-2f9d8',
    storageBucket: 'gym-training-app-2f9d8.appspot.com',
    iosClientId: '311082447008-91eod72cnitgeh05vhni79ir4hgd7mbp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEA-_zQU8y1uTn2EVP4s-BIC1kT7tYZ9I',
    appId: '1:311082447008:ios:edaa5950149052f0fe99c5',
    messagingSenderId: '311082447008',
    projectId: 'gym-training-app-2f9d8',
    storageBucket: 'gym-training-app-2f9d8.appspot.com',
    iosClientId: '311082447008-91eod72cnitgeh05vhni79ir4hgd7mbp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
